# Generated by Django 5.0.11 on 2025-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='transmetteur',
        ),
        migrations.AddField(
            model_name='courrier',
            name='emetteur',
            field=models.CharField(choices=[('Cabinet du président su Sénat(CABPSEN)', 'Cabinet du président su Sénat(CABPSEN)'), ('Sécrétaire Général(SG)', 'Sécrétaire Général(SG)'), ('Sécrétaire Général Adjoint 1(SGA1)', 'Sécrétaire Général Adjoint 1(SGA1)'), ('Sécrétaire Général Adjoint 2(SGA2)', 'Sécrétaire Général Adjoint 2(SGA2)'), ('Conseillé technique(CT)', 'Conseillé technique(CT)'), ('Chargé de mission(CM)', 'Chargé de mission(CM)'), ('Direction des missions internationales(DMI)', 'Direction des missions internationales(DMI)'), ('Direction des servides techniques commun(DSTC)', 'Direction des servides techniques commun(DSTC)'), ('Direction du budget de la solde(DBS)', 'Direction du budget de la solde(DBS)'), ('Direction agence comptable(AC)', 'Direction agence comptable(AC)'), ('Direction des actions sociales et médicales(DASM)', 'Direction des actions sociales et médicales(DASM)'), ("Direction de la traduction de l'interpretation(DTI)", "Direction de la traduction de l'interpretation(DTI)"), ('Direction de la coordination des services ratachés et des relations internationales', 'Direction de la coordination des services ratachés et des relations internationales'), ('Direction de la collectivité territorial décentralisées(DCTD)', 'Direction de la collectivité territorial décentralisées(DCTD)'), ('Direction des ressources humaines(DRH)', 'Direction des ressources humaines(DRH)'), ('Sercice des questeurs', 'Sercice des questeurs'), ('AUTRES...', 'AUTRES...')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
